### ISSUE TITLE
Assignment 5 Ready for Grading

### ISSUE THREAD

**Issue by mperezluna** [SES-5215-F2020/mperezluna-quant#5]
Hello, Assignment 5 is ready for grading. 

The file name is Assignment-5.html

The link is here:
https://ses-5215-f2020.github.io/mperezluna-quant/Assignment-5.html

**Comment by saratepfer** [comment]
nice job, Miguel. Your findings, visualizations, and interpretations look good. One note on code, below:

- line 20: r4place {r load libraries} with {r load libraries, messages = FALSE} to prevent R from printing unnecessary messages in your knitted markdown file.
